name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  test-macos:
    name: Test on Ruby ${{ matrix.ruby }} macOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.5', '2.4' ]
    steps:
      - uses: actions/checkout@master
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - name: Update gems
        run: |
          sudo gem install bundler --force
          bundle update --bundler
          bundle install --jobs 4 --retry 3
      - name: Use Metanorma
        run: |
          brew install yq metanorma
      - name: Metanorma compile
        env:
          JAVA_OPTS: "java.awt.headless=true"
        run: |
          export COMMIT_AUTHOR_EMAIL="$(yq r metanorma.yml metanorma.deploy.email)"
          make clean all publish
