name: ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  test-linux:
    name: Test on Ruby ${{ matrix.ruby }} Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6', '2.5', '2.4' ]
    steps:
      - uses: actions/checkout@master
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - name: Update gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Use Metanorma
        run: |
          curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | sudo bash
          sudo chown -R $USER:$(id -gn $USER) $HOME/.config
      - name: Install yq
        run: |
          sudo snap install yq
      - name: Metanorma compile
        env:
          JAVA_OPTS: "java.awt.headless=true"
        run: |
          export COMMIT_AUTHOR_EMAIL="$(yq r metanorma.yml metanorma.deploy.email)"
          source $HOME/.nvm/nvm.sh
          nvm use mn-node
          make clean all publish
