name: windows

on:
  push:
    branch: master
  pull_request:
    branches:
    - '**'

jobs:
  test-windows:
    name: Test on Ruby ${{ matrix.ruby }} Windows
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [ '2.6', '2.5', '2.4' ]
    steps:
      - uses: actions/checkout@master
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - name: Update gems
        shell: pwsh
        run: |
          gem install bundler -v "2.0.1"
          bundle config --local path vendor/bundle
          bundle update
          bundle install --jobs 4 --retry 3
      - name: Install yq
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/mikefarah/yq/releases/download/2.4.0/yq_windows_amd64.exe " -OutFile ".\yq.exe"
      - name: Metanorma compile
        run: |
          make -f Makefile.win clean all publish SHELL=cmd
