version: '{build}'

cache:
  - vendor/bundle

environment:
  matrix:
    - RUBY_VERSION: 25
    - RUBY_VERSION: 24
    - RUBY_VERSION: _trunk

matrix:
  allow_failures:
    - RUBY_VERSION: _trunk

install:
  - ps: . { iwr -useb https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/appveyor.ps1 } | iex
  - ps: Invoke-WebRequest -Uri "https://github.com/mikefarah/yq/releases/download/2.4.0/yq_windows_amd64.exe " -OutFile ".\yq.exe"
  - refreshenv
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle update

build_script:
  - make -f Makefile.win clean all publish SHELL=cmd
  - exit /B %ERRORLEVEL%
  - echo "Test DONE"

after_build:
  - 7z a %APPVEYOR_BUILD_FOLDER%\result.zip %APPVEYOR_BUILD_FOLDER%\*.pdf
  - 7z a %APPVEYOR_BUILD_FOLDER%\result.zip %APPVEYOR_BUILD_FOLDER%\*.html
  - 7z a %APPVEYOR_BUILD_FOLDER%\result.zip %APPVEYOR_BUILD_FOLDER%\*.xml
  - 7z a %APPVEYOR_BUILD_FOLDER%\result.zip %APPVEYOR_BUILD_FOLDER%\*.doc
  - 7z a %APPVEYOR_BUILD_FOLDER%\result.zip %APPVEYOR_BUILD_FOLDER%\*.adoc
  - 7z a %APPVEYOR_BUILD_FOLDER%\result.zip %APPVEYOR_BUILD_FOLDER%\images*
  - 7z a %APPVEYOR_BUILD_FOLDER%\result.zip %APPVEYOR_BUILD_FOLDER%\reference-docs*

artifacts:
  - path: result.zip
    name: result.zip
