name: ubuntu

on: [push, pull_request]

jobs:
  test-linux:
    name: Test on Ruby ${{ matrix.ruby }} Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.5', '2.4' ]
    steps:
      - uses: actions/checkout@master
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - name: Update gems
        run: |
          gem install bundler -v "~> 2"
          bundle update --bundler
          bundle install --jobs 4 --retry 3
      - name: Use Metanorma
        run: |
          sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash"
          sudo apt-get install -y libxml2-dev libxslt1-dev libicu-dev zlib1g-dev
      - name: Install yq
        run: |
          sudo snap install yq
      - name: Metanorma compile
        env:
          JAVA_OPTS: "java.awt.headless=true"
        run: |
          export COMMIT_AUTHOR_EMAIL="$(yq r metanorma.yml metanorma.deploy.email)"
          make clean all publish
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: |
          bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/deploy-to-gh-pages.sh | bash"