---
repos:
  isodoc:
    .github/workflows/macos.yml: gh-actions/puppeteer/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/puppeteer/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/puppeteer/windows.yml
  metanorma-ogc:
    .github/workflows/macos.yml: gh-actions/puppeteer/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/puppeteer/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/puppeteer/windows.yml
  metanorma-model-standoc:
    .github/workflows/macos.yml: gh-actions/model/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/model/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/model/windows.yml
  relaton-bib:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  relaton-iso-bib:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  metanorma-model-gb:
    .github/workflows/macos.yml: gh-actions/model/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/model/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/model/windows.yml
  relaton-iso:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  metanorma-model-iso:
    .github/workflows/macos.yml: gh-actions/model/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/model/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/model/windows.yml
  unece-cefact-plenary-2018-6:
    .github/workflows/ubuntu.yml: gh-actions/publish/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/publish/windows.yml
  metanorma-m3d:
    .github/workflows/macos.yml: gh-actions/puppeteer/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/puppeteer/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/puppeteer/windows.yml
  metanorma-model-unece:
    .github/workflows/macos.yml: gh-actions/model/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/model/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/model/windows.yml
  cnccs:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  metanorma-csd:
    .github/workflows/macos.yml: gh-actions/puppeteer/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/puppeteer/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/puppeteer/windows.yml
  metanorma-vsd:
    .github/workflows/macos.yml: gh-actions/puppeteer/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/puppeteer/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/puppeteer/windows.yml
  csd-public-documents:
    .github/workflows/ubuntu.yml: gh-actions/publish/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/publish/windows.yml
  metanorma-rsd:
    .github/workflows/macos.yml: gh-actions/plantuml/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/plantuml/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/plantuml/windows.yml
  relaton-models:
    .github/workflows/macos.yml: gh-actions/model/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/model/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/model/windows.yml
  metanorma-sample:
    .github/workflows/macos.yml: gh-actions/puppeteer/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/puppeteer/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/puppeteer/windows.yml
  isoics:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  iso690render:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  metanorma-mpfd:
    .github/workflows/macos.yml: gh-actions/puppeteer/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/puppeteer/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/puppeteer/windows.yml
  metanorma-model-itu:
    .github/workflows/macos.yml: gh-actions/model/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/model/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/model/windows.yml
  metanorma-model-csand:
    .github/workflows/macos.yml: gh-actions/model/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/model/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/model/windows.yml
  csa-ccm-tools:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  unicode2latex:
    .github/workflows/macos.yml: gh-actions/plantuml/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/plantuml/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/plantuml/windows.yml
  html2doc:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  ogc-wfs:
    .github/workflows/ubuntu.yml: gh-actions/publish/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/publish/windows.yml
  metanorma-model-nist:
    .github/workflows/macos.yml: gh-actions/model/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/model/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/model/windows.yml
  basicdoc-models:
    .github/workflows/macos.yml: gh-actions/model/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/model/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/model/windows.yml
  metanorma-model-csd:
    .github/workflows/macos.yml: gh-actions/model/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/model/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/model/windows.yml
  metanorma-gb:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  metanorma-model-m3d:
    .github/workflows/macos.yml: gh-actions/model/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/model/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/model/windows.yml
  relaton-iec:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  metanorma-nist:
    .github/workflows/macos.yml: gh-actions/puppeteer/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/puppeteer/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/puppeteer/windows.yml
  metanorma-iec:
    .github/workflows/macos.yml: gh-actions/puppeteer/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/puppeteer/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/puppeteer/windows.yml
  metanorma-ietf:
    .github/workflows/macos.yml: gh-actions/xml2rfc/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/xml2rfc/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/xml2rfc/windows.yml
  asciidoctor-rfc:
    .github/workflows/macos.yml: gh-actions/xml2rfc/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/xml2rfc/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/xml2rfc/windows.yml
  metanorma-standoc:
    .github/workflows/macos.yml: gh-actions/latexml/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/latexml/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/latexml/windows.yml
  metanorma-iso:
    .github/workflows/macos.yml: gh-actions/plantuml/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/plantuml/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/plantuml/windows.yml
  metanorma-unece:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  metanorma-model-ogc:
    .github/workflows/macos.yml: gh-actions/model/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/model/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/model/windows.yml
  relaton-server-csd:
    .github/workflows/macos.yml: gh-actions/puppeteer/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/puppeteer/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/puppeteer/windows.yml
  reverse_asciidoctor:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  isodoc-rice:
    .github/workflows/ubuntu.yml: gh-actions/publish/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/publish/windows.yml
  relaton-gb:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  gb-agencies:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  relaton-cli:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  mathml2asciimath:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  metanorma-itu:
    .github/workflows/macos.yml: gh-actions/puppeteer/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/puppeteer/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/puppeteer/windows.yml
  relaton:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  metanorma:
    .github/workflows/macos.yml: gh-actions/puppeteer/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/puppeteer/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/puppeteer/windows.yml
  relaton-itu:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  omml2mathml:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  metanorma-model-rsd:
    .github/workflows/macos.yml: gh-actions/model/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/model/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/model/windows.yml
  mn-ogc-documents:
    .github/workflows/ubuntu.yml: gh-actions/publish/ubuntu.yml
  mn-itu-docs:
    .github/workflows/ubuntu.yml: gh-actions/publish/ubuntu.yml
  mn-iec-docs:
    .github/workflows/ubuntu.yml: gh-actions/publish/ubuntu.yml
  unece-docs:
    .github/workflows/ubuntu.yml: gh-actions/publish/ubuntu.yml
  mpfd-documents:
    .github/workflows/ubuntu.yml: gh-actions/publish/ubuntu.yml
  metanorma-acme:
    .github/workflows/macos.yml: gh-actions/puppeteer/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/puppeteer/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/puppeteer/windows.yml
  iev:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  # metanorma-cli: unique config
  relaton-ietf:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  metanorma-csand:
    .github/workflows/macos.yml: gh-actions/plantuml/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/plantuml/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/plantuml/windows.yml
  relaton-nist:
    .github/workflows/macos.yml: gh-actions/master/macos.yml
    .github/workflows/ubuntu.yml: gh-actions/master/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/master/windows.yml
  # rfc2mn: unique config
  ogc-tcpnp:
    .github/workflows/ubuntu.yml: gh-actions/publish/ubuntu.yml
    .github/workflows/windows.yml: gh-actions/publish/windows.yml
  mn-templates-csd:
    .github/workflows/defaults.yml: gh-actions/templates/defaults.yml
    .github/workflows/windows.yml: gh-actions/templates/windows.yml
  mn-templates-ogc:
    .github/workflows/defaults.yml: gh-actions/templates/defaults.yml
    .github/workflows/windows.yml: gh-actions/templates/windows.yml
  mn-templates-iso:
    .github/workflows/defaults.yml: gh-actions/templates/defaults.yml
    .github/workflows/windows.yml: gh-actions/templates/windows.yml
  mn-templates-ietf:
    .github/workflows/defaults.yml: gh-actions/templates/defaults.yml
    .github/workflows/windows.yml: gh-actions/templates/windows.yml
  iso-bib-item:
    .github/workflows/defaults.yml: gh-actions/templates/defaults.yml
    .github/workflows/windows.yml: gh-actions/templates/windows.yml
  relaton-iev:
    .github/workflows/defaults.yml: gh-actions/templates/defaults.yml
    .github/workflows/windows.yml: gh-actions/templates/windows.yml
settings:
  pr: true
