---
repos:
  isodoc:
    .travis.yml: travis/puppeteer.yml
    appveyor.yml: appveyor/master.yml
  metanorma-ogc:
    .travis.yml: travis/puppeteer.yml
    appveyor.yml: appveyor/master.yml
  metanorma-model-standoc:
    .travis.yml: travis/plantuml.make.all.yml
  relaton-bib:
    appveyor.yml: appveyor/master.yml
    .travis.yml: travis/master.yml
  relaton-iso-bib:
    appveyor.yml: appveyor/master.yml
    .travis.yml: travis/master.yml
  metanorma-model-gb:
    .travis.yml: travis/plantuml.make.all.yml
  relaton-iso:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
  metanorma-model-iso:
    .travis.yml: travis/plantuml.make.all.yml
  unece-cefact-plenary-2018-6:
    .travis.yml: travis/linux.publish.yml
    appveyor.yml: appveyor/publish.yml
  metanorma-m3d:
    .travis.yml: travis/puppeteer.yml
    appveyor.yml: appveyor/master.yml
  metanorma-model-unece:
    .travis.yml: travis/plantuml.make.all.yml
  cnccs:
    appveyor.yml: appveyor/master.yml
    .travis.yml: travis/master.yml
  metanorma-csd:
    .travis.yml: travis/puppeteer.yml
    appveyor.yml: appveyor/master.yml
  metanorma-vsd:
    .travis.yml: travis/puppeteer.yml
    appveyor.yml: appveyor/master.yml
  csd-public-documents:
    .travis.yml: travis/linux.publish.yml
    appveyor.yml: appveyor/publish.yml
  metanorma-rsd:
    .travis.yml: travis/puppeteer.plantuml.yml
    appveyor.yml: appveyor/master.yml
  relaton-models:
    .travis.yml: travis/plantuml.make.all.yml
  metanorma-sample:
    .travis.yml: travis/puppeteer.yml
    appveyor.yml: appveyor/master.yml
  isoics:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
  iso690render:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
  metanorma-mpfd:
    .travis.yml: travis/puppeteer.yml
    appveyor.yml: appveyor/master.yml
  metanorma-model-itu:
    .travis.yml: travis/plantuml.make.all.yml
  metanorma-model-csand:
    .travis.yml: travis/plantuml.make.all.yml
  csa-ccm-tools:
    .travis.yml: travis/master-2.3.yml
    appveyor.yml: appveyor/master-2.3.yml
  unicode2latex:
    .travis.yml: travis/plantuml.yml
    appveyor.yml: appveyor/master.yml
  html2doc:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
  ogc-wfs:
    .travis.yml: travis/linux.publish.yml
    appveyor.yml: appveyor/publish.yml
  metanorma-model-nist:
    .travis.yml: travis/plantuml.make.all.yml
  basicdoc-models:
    .travis.yml: travis/plantuml.make.all.yml
  metanorma-model-csd:
    .travis.yml: travis/plantuml.make.all.yml
  metanorma-gb:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
  metanorma-model-m3d:
    .travis.yml: travis/plantuml.make.all.yml
  relaton-iec:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
  metanorma-nist:
    .travis.yml: travis/puppeteer.yml
    appveyor.yml: appveyor/master.yml
  metanorma-ietf:
    .travis.yml: travis/xml2rfc.yml
    appveyor.yml: appveyor/xml2rfc.yml
  metanorma-standoc:
    .travis.yml: travis/puppeteer.plantuml.latexml.yml
    appveyor.yml: appveyor/master.yml
  metanorma-iso:
    .travis.yml: travis/puppeteer.plantuml.yml
    appveyor.yml: appveyor/master.yml
  metanorma-unece:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
  metanorma-model-ogc:
    .travis.yml: travis/plantuml.make.all.yml
  relaton-server-csd:
    .travis.yml: travis/puppeteer.yml
  reverse_asciidoctor:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
  isodoc-rice:
    .travis.yml: travis/linux.publish.yml
    appveyor.yml: appveyor/publish.yml
  relaton-gb:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
  gb-agencies:
    appveyor.yml: appveyor/master.yml
    .travis.yml: travis/master.yml
  relaton-cli:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
  mathml2asciimath:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
  metanorma-itu:
    .travis.yml: travis/puppeteer.yml
    appveyor.yml: appveyor/master.yml
  relaton:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
  metanorma:
    .travis.yml: travis/puppeteer.yml
    appveyor.yml: appveyor/master.yml
  relaton-itu:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
  omml2mathml:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
  metanorma-model-rsd:
    .travis.yml: travis/plantuml.make.all.yml
  mn-ogc-documents:
    .travis.yml: travis/linux.publish.yml
  mn-itu-docs:
    .travis.yml: travis/linux.publish.yml
  mn-iec-docs:
    .travis.yml: travis/linux.publish.yml
  unece-docs:
    .travis.yml: travis/linux.publish.yml
  mpfd-documents:
    .travis.yml: travis/linux.publish.yml
  metanorma-acme:
    .travis.yml: travis/puppeteer.yml
    appveyor.yml: appveyor/master.yml
  iev:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
  metanorma-cli:
    appveyor.yml: appveyor/master.yml
  relaton-ietf:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
  metanorma-csand:
    .travis.yml: travis/puppeteer.plantuml.yml
    appveyor.yml: appveyor/master.yml
  relaton-nist:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
  # rfc2mn: unique config
  ogc-tcpnp:
    .travis.yml: travis/linux.publish.yml
    appveyor.yml: appveyor/publish.yml
  mn-templates-csd:
    .travis.yml: travis/templates.yml
    appveyor.yml: appveyor/templates.yml
  mn-templates-ogc:
    .travis.yml: travis/templates.yml
    appveyor.yml: appveyor/templates.yml
  mn-templates-iso:
    .travis.yml: travis/templates.yml
    appveyor.yml: appveyor/templates.yml
  mn-templates-ietf:
    .travis.yml: travis/templates.yml
    appveyor.yml: appveyor/templates.yml
  iso-bib-item:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
  relaton-iev:
    .travis.yml: travis/master.yml
    appveyor.yml: appveyor/master.yml
settings:
  pr: true
