language: ruby
cache: bundler
os:
- linux
- osx
rvm:
- 2.5
- 2.4
- ruby-head
before_install: 
- nvm install 8
- npm install -g puppeteer
- npm install
- gem install bundler -v "~> 2"
- bundle update
matrix:
  allow_failures:
    - rvm: ruby-head

