name: keep-alive
on:
  workflow_call:

jobs:
  keep-alive:
    name: Keep alive GHA
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: gautamkrishnar/keepalive-workflow@v1
